package com.test.importproducts;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ImportProduct implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ImportProduct() {
    }




}